version: "3.2"

services:
    kabocha-node:
        container_name: kabocha-node
        image: decentration/kabocha:0.9.8
        ports:
          - "9944:9944"
          - "9933:9933"
          - "40333:40333"
        command: bash -c "./kabocha-node/target/release/parachain-collator --collator --parachain-id 2001 --force-authoring --port 40333 --ws-port 8844 --rpc-cors all -- --execution wasm --chain /specs/rococo-chachacha.json"
        volumes:
          - "kabocha_collator_1:/data"
          - "chachacha_spec:/specs"
volumes:
    kabocha_collator_1:
    chachacha_spec:


